# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb6ba08893fb4a72362dd6884cfbc188710b5e072ac6774303c8c83db28116e2dfae0e1c6f85af0128c195bbf101e6aa0b02a471ee390c63a312f48e640197eb

test:
  secret_key_base: a23cdbf5b8ef9fea842a96bb73bbf2d6961e3827b962f94d7b607277d86b03fbc6512d76f4950a616fc0064c2f1c7068fe78eeb390fb4f48d4622fc1454f8af5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
